// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Person.pb.h"
// @@protoc_insertion_point(imports)

@implementation PersonRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [PersonRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface Person ()
@property (strong) PBAppendableArray * myfieldArray;
@end

@implementation Person

@synthesize myfieldArray;
@dynamic myfield;
- (void) dealloc {
  self.myfieldArray = nil;
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static Person* defaultPersonInstance = nil;
+ (void) initialize {
  if (self == [Person class]) {
    defaultPersonInstance = [[Person alloc] init];
  }
}
+ (Person*) defaultInstance {
  return defaultPersonInstance;
}
- (Person*) defaultInstance {
  return defaultPersonInstance;
}
- (PBArray *)myfield {
  return myfieldArray;
}
- (unsigned long)myfieldAtIndex:(NSUInteger)index {
  return [myfieldArray uint32AtIndex:index];
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  const NSUInteger myfieldArrayCount = self.myfieldArray.count;
  if (myfieldArrayCount > 0) {
    const unsigned long *values = (const unsigned long *)self.myfieldArray.data;
    for (NSUInteger i = 0; i < myfieldArrayCount; ++i) {
      [output writeUInt32:1 value:values[i]];
    }
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (long) serializedSize {
  long size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  {
    NSInteger dataSize = 0;
    const NSUInteger count = self.myfieldArray.count;
    const unsigned long *values = (const unsigned long *)self.myfieldArray.data;
    for (NSUInteger i = 0; i < count; ++i) {
      dataSize += computeUInt32SizeNoTag(values[i]);
    }
    size_ += dataSize;
    size_ += 1 * count;
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (Person*) parseFromData:(NSData*) data {
  return (Person*)[[[Person builder] mergeFromData:data] build];
}
+ (Person*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Person*)[[[Person builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Person*) parseFromInputStream:(NSInputStream*) input {
  return (Person*)[[[Person builder] mergeFromInputStream:input] build];
}
+ (Person*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Person*)[[[Person builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Person*)[[[Person builder] mergeFromCodedInputStream:input] build];
}
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Person*)[[[Person builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PersonBuilder*) builder {
  return [[PersonBuilder alloc] init];
}
+ (PersonBuilder*) builderWithPrototype:(Person*) prototype {
  return [[Person builder] mergeFrom:prototype];
}
- (PersonBuilder*) builder {
  return [Person builder];
}
- (PersonBuilder*) toBuilder {
  return [Person builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  [self.myfieldArray enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@: %@\n", indent, @"myfield", obj];
  }];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[Person class]]) {
    return NO;
  }
  Person *otherMessage = other;
  return
      [self.myfieldArray isEqualToArray:otherMessage.myfieldArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  [self.myfieldArray enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [obj longValue];
  }];
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PersonBuilder()
@property (strong) Person* result;
@end

@implementation PersonBuilder
@synthesize result;
- (void) dealloc {
  self.result = nil;
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[Person alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PersonBuilder*) clear {
  self.result = [[Person alloc] init];
  return self;
}
- (PersonBuilder*) clone {
  return [Person builderWithPrototype:result];
}
- (Person*) defaultInstance {
  return [Person defaultInstance];
}
- (Person*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Person*) buildPartial {
  Person* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (PersonBuilder*) mergeFrom:(Person*) other {
  if (other == [Person defaultInstance]) {
    return self;
  }
  if (other.myfieldArray.count > 0) {
    if (result.myfieldArray == nil) {
      result.myfieldArray = [other.myfieldArray copy];
    } else {
      [result.myfieldArray appendArray:other.myfieldArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PersonBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PersonBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    NSInteger tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self addMyfield:[input readUInt32]];
        break;
      }
    }
  }
}
- (PBAppendableArray *)myfield {
  return result.myfieldArray;
}
- (unsigned long)myfieldAtIndex:(NSUInteger)index {
  return [result myfieldAtIndex:index];
}
- (PersonBuilder *)addMyfield:(unsigned long)value {
  if (result.myfieldArray == nil) {
    result.myfieldArray = [PBAppendableArray arrayWithValueType:PBArrayValueTypeUInt32];
  }
  [result.myfieldArray addUint32:value];
  return self;
}
- (PersonBuilder *)setMyfieldArray:(NSArray *)array {
  result.myfieldArray = [PBAppendableArray arrayWithArray:array valueType:PBArrayValueTypeUInt32];
  return self;
}
- (PersonBuilder *)setMyfieldValues:(const unsigned long *)values count:(NSUInteger)count {
  result.myfieldArray = [PBAppendableArray arrayWithValues:values count:count valueType:PBArrayValueTypeUInt32];
  return self;
}
- (PersonBuilder *)clearMyfield {
  result.myfieldArray = nil;
  return self;
}
@end

@interface ExampleObject ()
@property (strong) PBAppendableArray * exampleFieldArray;
@end

@implementation ExampleObject

@synthesize exampleFieldArray;
@dynamic exampleField;
- (void) dealloc {
  self.exampleFieldArray = nil;
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static ExampleObject* defaultExampleObjectInstance = nil;
+ (void) initialize {
  if (self == [ExampleObject class]) {
    defaultExampleObjectInstance = [[ExampleObject alloc] init];
  }
}
+ (ExampleObject*) defaultInstance {
  return defaultExampleObjectInstance;
}
- (ExampleObject*) defaultInstance {
  return defaultExampleObjectInstance;
}
- (PBArray *)exampleField {
  return exampleFieldArray;
}
- (Float64)exampleFieldAtIndex:(NSUInteger)index {
  return [exampleFieldArray doubleAtIndex:index];
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  const NSUInteger exampleFieldArrayCount = self.exampleFieldArray.count;
  if (exampleFieldArrayCount > 0) {
    const Float64 *values = (const Float64 *)self.exampleFieldArray.data;
    for (NSUInteger i = 0; i < exampleFieldArrayCount; ++i) {
      [output writeDouble:7 value:values[i]];
    }
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (long) serializedSize {
  long size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  {
    NSInteger dataSize = 0;
    const NSUInteger count = self.exampleFieldArray.count;
    dataSize = 8 * count;
    size_ += dataSize;
    size_ += 1 * count;
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ExampleObject*) parseFromData:(NSData*) data {
  return (ExampleObject*)[[[ExampleObject builder] mergeFromData:data] build];
}
+ (ExampleObject*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ExampleObject*)[[[ExampleObject builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ExampleObject*) parseFromInputStream:(NSInputStream*) input {
  return (ExampleObject*)[[[ExampleObject builder] mergeFromInputStream:input] build];
}
+ (ExampleObject*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ExampleObject*)[[[ExampleObject builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ExampleObject*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ExampleObject*)[[[ExampleObject builder] mergeFromCodedInputStream:input] build];
}
+ (ExampleObject*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ExampleObject*)[[[ExampleObject builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ExampleObjectBuilder*) builder {
  return [[ExampleObjectBuilder alloc] init];
}
+ (ExampleObjectBuilder*) builderWithPrototype:(ExampleObject*) prototype {
  return [[ExampleObject builder] mergeFrom:prototype];
}
- (ExampleObjectBuilder*) builder {
  return [ExampleObject builder];
}
- (ExampleObjectBuilder*) toBuilder {
  return [ExampleObject builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  [self.exampleFieldArray enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@: %@\n", indent, @"exampleField", obj];
  }];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[ExampleObject class]]) {
    return NO;
  }
  ExampleObject *otherMessage = other;
  return
      [self.exampleFieldArray isEqualToArray:otherMessage.exampleFieldArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  [self.exampleFieldArray enumerateObjectsUsingBlock:^(id obj, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [obj longValue];
  }];
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface ExampleObjectBuilder()
@property (strong) ExampleObject* result;
@end

@implementation ExampleObjectBuilder
@synthesize result;
- (void) dealloc {
  self.result = nil;
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[ExampleObject alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ExampleObjectBuilder*) clear {
  self.result = [[ExampleObject alloc] init];
  return self;
}
- (ExampleObjectBuilder*) clone {
  return [ExampleObject builderWithPrototype:result];
}
- (ExampleObject*) defaultInstance {
  return [ExampleObject defaultInstance];
}
- (ExampleObject*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ExampleObject*) buildPartial {
  ExampleObject* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (ExampleObjectBuilder*) mergeFrom:(ExampleObject*) other {
  if (other == [ExampleObject defaultInstance]) {
    return self;
  }
  if (other.exampleFieldArray.count > 0) {
    if (result.exampleFieldArray == nil) {
      result.exampleFieldArray = [other.exampleFieldArray copy];
    } else {
      [result.exampleFieldArray appendArray:other.exampleFieldArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ExampleObjectBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ExampleObjectBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    NSInteger tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 57: {
        [self addExampleField:[input readDouble]];
        break;
      }
    }
  }
}
- (PBAppendableArray *)exampleField {
  return result.exampleFieldArray;
}
- (Float64)exampleFieldAtIndex:(NSUInteger)index {
  return [result exampleFieldAtIndex:index];
}
- (ExampleObjectBuilder *)addExampleField:(Float64)value {
  if (result.exampleFieldArray == nil) {
    result.exampleFieldArray = [PBAppendableArray arrayWithValueType:PBArrayValueTypeDouble];
  }
  [result.exampleFieldArray addDouble:value];
  return self;
}
- (ExampleObjectBuilder *)setExampleFieldArray:(NSArray *)array {
  result.exampleFieldArray = [PBAppendableArray arrayWithArray:array valueType:PBArrayValueTypeDouble];
  return self;
}
- (ExampleObjectBuilder *)setExampleFieldValues:(const Float64 *)values count:(NSUInteger)count {
  result.exampleFieldArray = [PBAppendableArray arrayWithValues:values count:count valueType:PBArrayValueTypeDouble];
  return self;
}
- (ExampleObjectBuilder *)clearExampleField {
  result.exampleFieldArray = nil;
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
