// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class PublicImportMessage;
@class PublicImportMessageBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface UnittestImportPublicRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PublicImportMessage : PBGeneratedMessage {
@private
  BOOL hasE_:1;
  SInt32 e;
}
- (BOOL) hasE;
@property (readonly) SInt32 e;

+ (PublicImportMessage*) defaultInstance;
- (PublicImportMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PublicImportMessageBuilder*) builder;
+ (PublicImportMessageBuilder*) builder;
+ (PublicImportMessageBuilder*) builderWithPrototype:(PublicImportMessage*) prototype;
- (PublicImportMessageBuilder*) toBuilder;

+ (PublicImportMessage*) parseFromData:(NSData*) data;
+ (PublicImportMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PublicImportMessage*) parseFromInputStream:(NSInputStream*) input;
+ (PublicImportMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PublicImportMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PublicImportMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PublicImportMessageBuilder : PBGeneratedMessageBuilder {
@private
  PublicImportMessage* result;
}

- (PublicImportMessage*) defaultInstance;

- (PublicImportMessageBuilder*) clear;
- (PublicImportMessageBuilder*) clone;

- (PublicImportMessage*) build;
- (PublicImportMessage*) buildPartial;

- (PublicImportMessageBuilder*) mergeFrom:(PublicImportMessage*) other;
- (PublicImportMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PublicImportMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasE;
- (SInt32) e;
- (PublicImportMessageBuilder*) setE:(SInt32) value;
- (PublicImportMessageBuilder*) clearE;
@end


// @@protoc_insertion_point(global_scope)
