// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Unittest_import_public_lite.pb.h"
// @@protoc_insertion_point(imports)

@implementation UnittestImportPublicLiteRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [UnittestImportPublicLiteRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface PublicImportMessageLite ()
@property SInt32 e;
@end

@implementation PublicImportMessageLite

- (BOOL) hasE {
  return !!hasE_;
}
- (void) setHasE:(BOOL) value_ {
  hasE_ = !!value_;
}
@synthesize e;
- (id) init {
  if ((self = [super init])) {
    self.e = 0;
  }
  return self;
}
static PublicImportMessageLite* defaultPublicImportMessageLiteInstance = nil;
+ (void) initialize {
  if (self == [PublicImportMessageLite class]) {
    defaultPublicImportMessageLiteInstance = [[PublicImportMessageLite alloc] init];
  }
}
+ (PublicImportMessageLite*) defaultInstance {
  return defaultPublicImportMessageLiteInstance;
}
- (PublicImportMessageLite*) defaultInstance {
  return defaultPublicImportMessageLiteInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasE) {
    [output writeInt32:1 value:self.e];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasE) {
    size_ += computeInt32Size(1, self.e);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (PublicImportMessageLite*) parseFromData:(NSData*) data {
  return (PublicImportMessageLite*)[[[PublicImportMessageLite builder] mergeFromData:data] build];
}
+ (PublicImportMessageLite*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PublicImportMessageLite*)[[[PublicImportMessageLite builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PublicImportMessageLite*) parseFromInputStream:(NSInputStream*) input {
  return (PublicImportMessageLite*)[[[PublicImportMessageLite builder] mergeFromInputStream:input] build];
}
+ (PublicImportMessageLite*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PublicImportMessageLite*)[[[PublicImportMessageLite builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PublicImportMessageLite*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PublicImportMessageLite*)[[[PublicImportMessageLite builder] mergeFromCodedInputStream:input] build];
}
+ (PublicImportMessageLite*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PublicImportMessageLite*)[[[PublicImportMessageLite builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PublicImportMessageLiteBuilder*) builder {
  return [[PublicImportMessageLiteBuilder alloc] init];
}
+ (PublicImportMessageLiteBuilder*) builderWithPrototype:(PublicImportMessageLite*) prototype {
  return [[PublicImportMessageLite builder] mergeFrom:prototype];
}
- (PublicImportMessageLiteBuilder*) builder {
  return [PublicImportMessageLite builder];
}
- (PublicImportMessageLiteBuilder*) toBuilder {
  return [PublicImportMessageLite builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasE) {
    [output appendFormat:@"%@%@: %@\n", indent, @"e", [NSNumber numberWithInteger:self.e]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[PublicImportMessageLite class]]) {
    return NO;
  }
  PublicImportMessageLite *otherMessage = other;
  return
      self.hasE == otherMessage.hasE &&
      (!self.hasE || self.e == otherMessage.e) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasE) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.e] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface PublicImportMessageLiteBuilder()
@property (strong) PublicImportMessageLite* result;
@end

@implementation PublicImportMessageLiteBuilder
@synthesize result;
- (id) init {
  if ((self = [super init])) {
    self.result = [[PublicImportMessageLite alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PublicImportMessageLiteBuilder*) clear {
  self.result = [[PublicImportMessageLite alloc] init];
  return self;
}
- (PublicImportMessageLiteBuilder*) clone {
  return [PublicImportMessageLite builderWithPrototype:result];
}
- (PublicImportMessageLite*) defaultInstance {
  return [PublicImportMessageLite defaultInstance];
}
- (PublicImportMessageLite*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PublicImportMessageLite*) buildPartial {
  PublicImportMessageLite* returnMe = result;
  self.result = nil;
  return returnMe;
}
- (PublicImportMessageLiteBuilder*) mergeFrom:(PublicImportMessageLite*) other {
  if (other == [PublicImportMessageLite defaultInstance]) {
    return self;
  }
  if (other.hasE) {
    [self setE:other.e];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PublicImportMessageLiteBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PublicImportMessageLiteBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setE:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasE {
  return result.hasE;
}
- (SInt32) e {
  return result.e;
}
- (PublicImportMessageLiteBuilder*) setE:(SInt32) value {
  result.hasE = YES;
  result.e = value;
  return self;
}
- (PublicImportMessageLiteBuilder*) clearE {
  result.hasE = NO;
  result.e = 0;
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
