// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Unittest_optimize_for.pb.h"
// @@protoc_insertion_point(imports)

@class BarRequest;
@class BarRequestBuilder;
@class BarResponse;
@class BarResponseBuilder;
@class FooClientMessage;
@class FooClientMessageBuilder;
@class FooRequest;
@class FooRequestBuilder;
@class FooResponse;
@class FooResponseBuilder;
@class FooServerMessage;
@class FooServerMessageBuilder;
@class ForeignMessage;
@class ForeignMessageBuilder;
@class ImportMessage;
@class ImportMessageBuilder;
@class MoreBytes;
@class MoreBytesBuilder;
@class MoreString;
@class MoreStringBuilder;
@class OneBytes;
@class OneBytesBuilder;
@class OneString;
@class OneStringBuilder;
@class OptionalGroup_extension;
@class OptionalGroup_extensionBuilder;
@class PublicImportMessage;
@class PublicImportMessageBuilder;
@class RepeatedGroup_extension;
@class RepeatedGroup_extensionBuilder;
@class SparseEnumMessage;
@class SparseEnumMessageBuilder;
@class TestAllExtensions;
@class TestAllExtensionsBuilder;
@class TestAllTypes;
@class TestAllTypesBuilder;
@class TestAllTypesNestedMessage;
@class TestAllTypesNestedMessageBuilder;
@class TestAllTypesOptionalGroup;
@class TestAllTypesOptionalGroupBuilder;
@class TestAllTypesRepeatedGroup;
@class TestAllTypesRepeatedGroupBuilder;
@class TestCamelCaseFieldNames;
@class TestCamelCaseFieldNamesBuilder;
@class TestCommentInjectionMessage;
@class TestCommentInjectionMessageBuilder;
@class TestDeprecatedFields;
@class TestDeprecatedFieldsBuilder;
@class TestDupFieldNumber;
@class TestDupFieldNumberBar;
@class TestDupFieldNumberBarBuilder;
@class TestDupFieldNumberBuilder;
@class TestDupFieldNumberFoo;
@class TestDupFieldNumberFooBuilder;
@class TestDynamicExtensions;
@class TestDynamicExtensionsBuilder;
@class TestDynamicExtensionsDynamicMessageType;
@class TestDynamicExtensionsDynamicMessageTypeBuilder;
@class TestEagerMessage;
@class TestEagerMessageBuilder;
@class TestEmbedOptimizedForSize;
@class TestEmbedOptimizedForSizeBuilder;
@class TestEmptyMessage;
@class TestEmptyMessageBuilder;
@class TestEmptyMessageWithExtensions;
@class TestEmptyMessageWithExtensionsBuilder;
@class TestExtremeDefaultValues;
@class TestExtremeDefaultValuesBuilder;
@class TestFieldOrderings;
@class TestFieldOrderingsBuilder;
@class TestForeignNested;
@class TestForeignNestedBuilder;
@class TestLazyMessage;
@class TestLazyMessageBuilder;
@class TestMultipleExtensionRanges;
@class TestMultipleExtensionRangesBuilder;
@class TestMutualRecursionA;
@class TestMutualRecursionABuilder;
@class TestMutualRecursionB;
@class TestMutualRecursionBBuilder;
@class TestNestedExtension;
@class TestNestedExtensionBuilder;
@class TestNestedMessageHasBits;
@class TestNestedMessageHasBitsBuilder;
@class TestNestedMessageHasBitsNestedMessage;
@class TestNestedMessageHasBitsNestedMessageBuilder;
@class TestOptimizedForSize;
@class TestOptimizedForSizeBuilder;
@class TestOptionalOptimizedForSize;
@class TestOptionalOptimizedForSizeBuilder;
@class TestPackedExtensions;
@class TestPackedExtensionsBuilder;
@class TestPackedTypes;
@class TestPackedTypesBuilder;
@class TestParsingMerge;
@class TestParsingMergeBuilder;
@class TestParsingMergeOptionalGroup;
@class TestParsingMergeOptionalGroupBuilder;
@class TestParsingMergeRepeatedFieldsGenerator;
@class TestParsingMergeRepeatedFieldsGeneratorBuilder;
@class TestParsingMergeRepeatedFieldsGeneratorGroup1;
@class TestParsingMergeRepeatedFieldsGeneratorGroup1Builder;
@class TestParsingMergeRepeatedFieldsGeneratorGroup2;
@class TestParsingMergeRepeatedFieldsGeneratorGroup2Builder;
@class TestParsingMergeRepeatedGroup;
@class TestParsingMergeRepeatedGroupBuilder;
@class TestReallyLargeTagNumber;
@class TestReallyLargeTagNumberBuilder;
@class TestRecursiveMessage;
@class TestRecursiveMessageBuilder;
@class TestRepeatedScalarDifferentTagSizes;
@class TestRepeatedScalarDifferentTagSizesBuilder;
@class TestRequired;
@class TestRequiredBuilder;
@class TestRequiredForeign;
@class TestRequiredForeignBuilder;
@class TestRequiredOptimizedForSize;
@class TestRequiredOptimizedForSizeBuilder;
@class TestUnpackedTypes;
@class TestUnpackedTypesBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface UnittestEmbedOptimizeForRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface TestEmbedOptimizedForSize : PBGeneratedMessage {
@private
  BOOL hasOptionalMessage_:1;
  TestOptimizedForSize* optionalMessage;
  NSMutableArray * repeatedMessageArray;
}
- (BOOL) hasOptionalMessage;
@property (readonly, strong) TestOptimizedForSize* optionalMessage;
@property (readonly, strong) NSArray * repeatedMessage;
- (TestOptimizedForSize*)repeatedMessageAtIndex:(NSUInteger)index;

+ (TestEmbedOptimizedForSize*) defaultInstance;
- (TestEmbedOptimizedForSize*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TestEmbedOptimizedForSizeBuilder*) builder;
+ (TestEmbedOptimizedForSizeBuilder*) builder;
+ (TestEmbedOptimizedForSizeBuilder*) builderWithPrototype:(TestEmbedOptimizedForSize*) prototype;
- (TestEmbedOptimizedForSizeBuilder*) toBuilder;

+ (TestEmbedOptimizedForSize*) parseFromData:(NSData*) data;
+ (TestEmbedOptimizedForSize*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestEmbedOptimizedForSize*) parseFromInputStream:(NSInputStream*) input;
+ (TestEmbedOptimizedForSize*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestEmbedOptimizedForSize*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TestEmbedOptimizedForSize*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestEmbedOptimizedForSizeBuilder : PBGeneratedMessageBuilder {
@private
  TestEmbedOptimizedForSize* result;
}

- (TestEmbedOptimizedForSize*) defaultInstance;

- (TestEmbedOptimizedForSizeBuilder*) clear;
- (TestEmbedOptimizedForSizeBuilder*) clone;

- (TestEmbedOptimizedForSize*) build;
- (TestEmbedOptimizedForSize*) buildPartial;

- (TestEmbedOptimizedForSizeBuilder*) mergeFrom:(TestEmbedOptimizedForSize*) other;
- (TestEmbedOptimizedForSizeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TestEmbedOptimizedForSizeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOptionalMessage;
- (TestOptimizedForSize*) optionalMessage;
- (TestEmbedOptimizedForSizeBuilder*) setOptionalMessage:(TestOptimizedForSize*) value;
- (TestEmbedOptimizedForSizeBuilder*) setOptionalMessageBuilder:(TestOptimizedForSizeBuilder*) builderForValue;
- (TestEmbedOptimizedForSizeBuilder*) mergeOptionalMessage:(TestOptimizedForSize*) value;
- (TestEmbedOptimizedForSizeBuilder*) clearOptionalMessage;

- (NSMutableArray *)repeatedMessage;
- (TestOptimizedForSize*)repeatedMessageAtIndex:(NSUInteger)index;
- (TestEmbedOptimizedForSizeBuilder *)addRepeatedMessage:(TestOptimizedForSize*)value;
- (TestEmbedOptimizedForSizeBuilder *)setRepeatedMessageArray:(NSArray *)array;
- (TestEmbedOptimizedForSizeBuilder *)clearRepeatedMessage;
@end


// @@protoc_insertion_point(global_scope)
