// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Unittest_empty.pb.h"
// @@protoc_insertion_point(imports)

@implementation UnittestEmptyRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [UnittestEmptyRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end


// @@protoc_insertion_point(global_scope)
