// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class TestMessage;
@class TestMessage_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef enum {
  TestEnumFoo = 1,
} TestEnum;

BOOL TestEnumIsValidValue(TestEnum value);


@interface UnittestNoGenericServicesRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
+ (id<PBExtensionField>) testExtension;
@end

@interface TestMessage : PBExtendableMessage {
@private
  BOOL hasA_:1;
  int32_t a;
}
- (BOOL) hasA;
@property (readonly) int32_t a;

+ (TestMessage*) defaultInstance;
- (TestMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TestMessage_Builder*) builder;
+ (TestMessage_Builder*) builder;
+ (TestMessage_Builder*) builderWithPrototype:(TestMessage*) prototype;
- (TestMessage_Builder*) toBuilder;

+ (TestMessage*) parseFromData:(NSData*) data;
+ (TestMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestMessage*) parseFromInputStream:(NSInputStream*) input;
+ (TestMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TestMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TestMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TestMessage_Builder : PBExtendableMessage_Builder {
@private
  TestMessage* result;
}

- (TestMessage*) defaultInstance;

- (TestMessage_Builder*) clear;
- (TestMessage_Builder*) clone;

- (TestMessage*) build;
- (TestMessage*) buildPartial;

- (TestMessage_Builder*) mergeFrom:(TestMessage*) other;
- (TestMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TestMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasA;
- (int32_t) a;
- (TestMessage_Builder*) setA:(int32_t) value;
- (TestMessage_Builder*) clearA;
@end

