// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Unittest_import_public_lite.pb.h"
// @@protoc_insertion_point(imports)

@class ImportMessageLite;
@class ImportMessageLiteBuilder;
@class PublicImportMessageLite;
@class PublicImportMessageLiteBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef enum {
  ImportEnumLiteImportLiteFoo = 7,
  ImportEnumLiteImportLiteBar = 8,
  ImportEnumLiteImportLiteBaz = 9,
} ImportEnumLite;

BOOL ImportEnumLiteIsValidValue(ImportEnumLite value);


@interface UnittestImportLiteRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ImportMessageLite : PBGeneratedMessage {
@private
  BOOL hasD_:1;
  long d;
}
- (BOOL) hasD;
@property (readonly) long d;

+ (ImportMessageLite*) defaultInstance;
- (ImportMessageLite*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ImportMessageLiteBuilder*) builder;
+ (ImportMessageLiteBuilder*) builder;
+ (ImportMessageLiteBuilder*) builderWithPrototype:(ImportMessageLite*) prototype;
- (ImportMessageLiteBuilder*) toBuilder;

+ (ImportMessageLite*) parseFromData:(NSData*) data;
+ (ImportMessageLite*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ImportMessageLite*) parseFromInputStream:(NSInputStream*) input;
+ (ImportMessageLite*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ImportMessageLite*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ImportMessageLite*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ImportMessageLiteBuilder : PBGeneratedMessage_Builder {
@private
  ImportMessageLite* result;
}

- (ImportMessageLite*) defaultInstance;

- (ImportMessageLiteBuilder*) clear;
- (ImportMessageLiteBuilder*) clone;

- (ImportMessageLite*) build;
- (ImportMessageLite*) buildPartial;

- (ImportMessageLiteBuilder*) mergeFrom:(ImportMessageLite*) other;
- (ImportMessageLiteBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ImportMessageLiteBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasD;
- (long) d;
- (ImportMessageLiteBuilder*) setD:(long) value;
- (ImportMessageLiteBuilder*) clearD;
@end


// @@protoc_insertion_point(global_scope)
