// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Unittest_import_public.pb.h"
// @@protoc_insertion_point(imports)

@class ImportMessage;
@class ImportMessageBuilder;
@class PublicImportMessage;
@class PublicImportMessageBuilder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif

typedef enum {
  ImportEnumImportFoo = 7,
  ImportEnumImportBar = 8,
  ImportEnumImportBaz = 9,
} ImportEnum;

BOOL ImportEnumIsValidValue(ImportEnum value);


@interface UnittestImportRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ImportMessage : PBGeneratedMessage {
@private
  BOOL hasD_:1;
  long d;
}
- (BOOL) hasD;
@property (readonly) long d;

+ (ImportMessage*) defaultInstance;
- (ImportMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ImportMessageBuilder*) builder;
+ (ImportMessageBuilder*) builder;
+ (ImportMessageBuilder*) builderWithPrototype:(ImportMessage*) prototype;
- (ImportMessageBuilder*) toBuilder;

+ (ImportMessage*) parseFromData:(NSData*) data;
+ (ImportMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ImportMessage*) parseFromInputStream:(NSInputStream*) input;
+ (ImportMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ImportMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ImportMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ImportMessageBuilder : PBGeneratedMessageBuilder {
@private
  ImportMessage* result;
}

- (ImportMessage*) defaultInstance;

- (ImportMessageBuilder*) clear;
- (ImportMessageBuilder*) clone;

- (ImportMessage*) build;
- (ImportMessage*) buildPartial;

- (ImportMessageBuilder*) mergeFrom:(ImportMessage*) other;
- (ImportMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ImportMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasD;
- (long) d;
- (ImportMessageBuilder*) setD:(long) value;
- (ImportMessageBuilder*) clearD;
@end


// @@protoc_insertion_point(global_scope)
